---
- name: install add-apt-repostory
  become: true
  apt: name=software-properties-common state=latest

- name: add webupd8team/java repositories
  become: true
  apt_repository: repo="ppa:webupd8team/java" state=present

- name: accept oracle license
  become: true
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install required software
  become: true
  apt: name={{item}} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - ca-certificates
    - oracle-java8-installer
    - oracle-java8-set-default
